name: 'Cache Azure Blob'
description: 'actions/cache@v3 for Azure Blob Storage (forked from whywaita/actions-cache-s3)'
author: 'madkoo'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache and restore'
    required: true
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.'
    required: false
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms'
    default: 'false'
    required: false
  fail-on-cache-miss:
    description: 'Fail the workflow if cache entry is not found'
    default: 'false'
    required: false
  lookup-only:
    description: 'Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache'
    default: 'false'
    required: false
  azure-blob-container:
    description: 'Azure Blob Storage container name to save cache'
    required: true
  azure-storage-account-name:
    description: 'Azure Storage account name'
    required: false
  azure-storage-account-key:
    description: 'Azure Storage account key'
    required: false
  azure-storage-connection-string:
    description: 'Azure Storage connection string (alternative to account name/key)'
    required: false
  azure-storage-sas-token:
    description: 'Azure Storage SAS token'
    required: false
  azure-blob-endpoint:
    description: 'Custom Azure Blob Storage endpoint (optional)'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
